
language: node_js
node_js:
  - "8"
install:
  - yarn install
# script: true

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: bash deploy.sh
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   on:
#     branch: master
#  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