# name: Build and Publish

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: enriikke/gatsby-gh-pages-action@v2
#         with:
#           access-token: ${{ secrets.ACTIONTOKEN }} // 自定义 scret name
#           deploy-branch: master
#           deploy-repo: GitAlphabet.github.io // 注意这里直接是仓库名称
#           folder: doc/.vuepress/dist

name: Build and Publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 构建部署
        run: bash deploy.sh
        # with:
          # access-token: ${{ secrets.ACTIONTOKEN }} # 自定义 scret name
          # deploy-branch: master
          # deploy-repo: GitAlphabet.github.io # 注意这里直接是仓库名称
          # folder: doc/.vuepress/dist
    

