name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        # with:
        #   access-token: ${{ secrets.ACTIONTOKEN }} # 自定义 scret name
        #   deploy-branch: master
        #   deploy-repo: GitAlphabet.github.io # 注意这里直接是仓库名称
        #   folder: doc/.vuepress/dist

      - name: Setup Node.js environment # 配置Node环境
        uses: actions/setup-node@v3.2.0 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "14.x"
    
      - name: install deps
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3	# 一个自动发布github pages的action
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }} 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
          external_repository: GitAlphabet/GitAlphabet.github.io	# 发布到哪个repo
          personal_token: ${{ secrets.ACTIONTOKEN }}	# 发布到其他repo需要提供上面生成的personal access token
          publish_dir: ./dist	# 注意这里指的是要发布哪个文件夹的内容，而不是指发布到目的仓库的什么位置，因为hugo默认生成静态网页到public文件夹，所以这里发布public文件夹里的内容
          publish_branch: master	# 发布到哪个branch
