name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Node.js environment # 配置Node环境
        uses: actions/setup-node@v3.2.0 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "14.x"
    
      - name: install deps
        run: yarn install

      - name: build
        run: yarn docs:build

      - name: deploy
        uses: crazy-max/ghaction-github-pages@v2
        # 环境变量
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONTOKEN }}
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
